apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: event-storming
  annotations:
    github.com/project-slug: thms/event-storming
    backstage.io/techdocs-ref: dir:.
  links:
    - title: Getting Started
      url: https://github.com/thms/event-storming/README.md
      type: Readme
      icon: github
spec:
  type: application
  lifecycle: experimental
  owner: thms